[
  ./runit
  ./dinit
  ./dumb-init
  ./initrd
  ./init.nix
  ./nixpkgs.nix
  ./system.nix
  ./system/toplevel.nix
  ./system/oci-image.nix
  ./system/run.nix
  ./system/bundle.nix
  ./system/initrd.nix
  ./assertions.nix
  ./bootloader
  ./nix.nix
  ./fstab.nix
  ./time.nix

  ./security/ca.nix

  ./misc/iana.nix

  ./environment.nix
  ./users.nix
  ./ids.nix

  ./services/apache2-nixos.nix
  ./services/nginx.nix
  ./services/gitea.nix
  ./services/getty.nix
  ./services/socklog.nix
  ./services/crond.nix
  ./services/hydra.nix
  ./services/postgresql.nix
  ./services/mysql.nix
  ./services/certbot.nix
  ./services/postfix.nix
  ./services/dovecot.nix
  ./services/pantalaimon.nix
  ./services/jmusicbot.nix
  ./services/php-fpm.nix
  ./services/minecraft.nix
  ./services/home-assistant.nix
  ./services/tmpfilesd.nix
  ./services/zigbee2mqtt.nix
  ./services/mosquitto.nix
  ./services/syncthing.nix
  ./services/synapse.nix
  ./services/dnsmasq.nix
  ./services/attic.nix
  ./services/ntfy-sh.nix
]
